### ISSUE TITLE
ImportError: No module named 'focus'

### ISSUE THREAD

**Issue by kdvalin** [kidcontact/focus-api#3]
**Problem:**

After installing required dependencies outlined in the README, and attempting to run the program using latest version of python3 on Debian 9.1 results in the following error.

`Traceback (most recent call last):`
`    File "app.py", line 8, in <module>`
`    from focus import parser`
`ImportError: No module named 'focus'`

**How to replicate:** 

Using a fresh install of Debian 9.1, run `apt install python3 and python3-pip`
Install dependencies as outlined in the [README](https://github.com/kidcontact/focus-api/blob/master/README.md)
Download source code or clone repository, and go into resulting directory
Run `pyhton3 focus/app.py`

**Comment by stephanlensky** [comment]
The error should be fixed in the latest commit. You'll also want to run `pip3 install parse`, since I realized that I forgot to include that dependency in the README.

BTW, mind if I ask what you're using this for? I know that there's likely a few compatibility problems with the Academy for Science and Design at the moment, since they just updated their UI this year and I've been too busy to see if it broke anything. I've also never been able to test this with any other schools, so I have no idea what will happen if you try to use it with anything else. Best of luck to you though, if you run into specific problems with another school I'll be happy to look into them, but depending on the amount of work needed to fix them I may not have time to. The primary goal of this project is and will always be to support ASD.

If you need any other help let me know.
